nome = str(input('Digite o nome completo: ')).strip()
print('Analisando o nome digitado....')
print('seu nome em maiusculas {}  '.format(nome.upper()))
print('seu nome em minusculas {}  '.format(nome.lower()))
print('seu nome com apenas a primeira letra em minuscula {}  '.format(nome.capitalize()))
print('seu nome com todas as iniciais em  maiusculas {}  '.format(nome.title()))
print('substituindo {}  '.format(nome.replace('wagner','morais')))
print('quantidade de caracteres {}  '.format(len(nome) - nome.count(' ')))
print('convertendo string para um lista {}  '.format(nome.split()))
print('Pesquisando os caracteres: {} '.format(nome.find(' ')))